<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-14 12:22
=======
# Generated by Django 5.0.4 on 2024-07-16 16:44
>>>>>>> 904a2987591481002d5da669047b61f78fb5b612

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("base", "0003_alter_room_options_room_participants"),
=======
        ('base', '0003_alter_room_options_room_participants'),
>>>>>>> 904a2987591481002d5da669047b61f78fb5b612
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name="message",
            options={"ordering": ["-updated", "-created"]},
=======
            name='message',
            options={'ordering': ['-updated', '-created']},
>>>>>>> 904a2987591481002d5da669047b61f78fb5b612
        ),
    ]
